name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - faiss-cpu
  - numpy
  - pip
  - pip:
      - fastapi
      - "uvicorn[standard]"
      - python-dotenv
      - requests
      - openai
      # Document parsing libraries
      - pypdf2
      - python-pptx
      - openpyxl
      # For sample doc generation
      - reportlab
